<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-VH56LQQ" ignored="0" name="Default test" tests="2" failures="1" timestamp="01 Aug 2018 17:29:14 GMT" time="42.861" errors="0">
  <testcase name="doLoginTest" time="0.169" classname="dfPack.tests.LoginTest">
    <skipped/>
  </testcase> <!-- doLoginTest -->
  <testcase name="doLoginTest" time="40.709" classname="dfPack.tests.LoginTest">
    <failure type="java.lang.AssertionError" message="CRMOption_cssselector holding the [class^=&amp;apos;xyz&amp;apos;] is not findable">
      <![CDATA[java.lang.AssertionError: CRMOption_cssselector holding the [class^='xyz'] is not findable
at org.testng.Assert.fail(Assert.java:96)
at dfPack.base.BaseTest.reportFail(BaseTest.java:209)
at dfPack.base.BaseTest.getElement(BaseTest.java:190)
at dfPack.base.BaseTest.isElementPresent(BaseTest.java:146)
at dfPack.base.BaseTest.doLogin(BaseTest.java:112)
at dfPack.tests.LoginTest.doLoginTest(LoginTest.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- doLoginTest -->
</testsuite> <!-- Default test -->
