<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="42861" started-at="2018-08-01T17:28:31Z" finished-at="2018-08-01T17:29:14Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="42861" started-at="2018-08-01T17:28:31Z" finished-at="2018-08-01T17:29:14Z">
      <class name="dfPack.tests.LoginTest">
        <test-method status="PASS" signature="init()[pri:0, instance:dfPack.tests.LoginTest@17d0008]" name="init" is-config="true" duration-ms="26" started-at="2018-08-01T17:28:31Z" finished-at="2018-08-01T17:28:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="SKIP" signature="doLoginTest(java.util.HashMap)[pri:0, instance:dfPack.tests.LoginTest@17d0008]" name="doLoginTest" duration-ms="169" started-at="2018-08-01T17:28:32Z" data-provider="getData" finished-at="2018-08-01T17:28:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=N, ExpectedResult=Failure, Username=seleniumbyarun99@gmail.com, Browser=Firefox, Password=Demopassword$}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test as the run mode is set to N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test as the run mode is set to N
at dfPack.tests.LoginTest.doLoginTest(LoginTest.java:63)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLoginTest -->
        <test-method status="PASS" signature="testClosure()[pri:0, instance:dfPack.tests.LoginTest@17d0008]" name="testClosure" is-config="true" duration-ms="362" started-at="2018-08-01T17:28:32Z" finished-at="2018-08-01T17:28:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testClosure -->
        <test-method status="FAIL" signature="doLoginTest(java.util.HashMap)[pri:0, instance:dfPack.tests.LoginTest@17d0008]" name="doLoginTest" duration-ms="40709" started-at="2018-08-01T17:28:33Z" data-provider="getData" finished-at="2018-08-01T17:29:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=Y, ExpectedResult=Success, Username=seleniumtraining11292017@gmail.com, Browser=Chrome, Password=SeleniumTester$}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[CRMOption_cssselector holding the [class^='xyz'] is not findable]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: CRMOption_cssselector holding the [class^='xyz'] is not findable
at org.testng.Assert.fail(Assert.java:96)
at dfPack.base.BaseTest.reportFail(BaseTest.java:209)
at dfPack.base.BaseTest.getElement(BaseTest.java:190)
at dfPack.base.BaseTest.isElementPresent(BaseTest.java:146)
at dfPack.base.BaseTest.doLogin(BaseTest.java:112)
at dfPack.tests.LoginTest.doLoginTest(LoginTest.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLoginTest -->
        <test-method status="PASS" signature="testClosure()[pri:0, instance:dfPack.tests.LoginTest@17d0008]" name="testClosure" is-config="true" duration-ms="945" started-at="2018-08-01T17:29:13Z" finished-at="2018-08-01T17:29:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testClosure -->
      </class> <!-- dfPack.tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
